### PR TITLE
Update dtoa to latest version

### PR DESCRIPTION
**Pull request by mato**
Update nolibc/dtoa.c to the latest version at http://www.netlib.org/fp/, with the following modifications:

- Perform arch-specific configuration inline in dtoa.c.
- Add and use a STRTOD_ONLY flag to compile only strtod() and its dependencies.
- Make gethex() static.

Further, nolibc/dtoa.c is compiled with -fno-strict-aliasing. This is strictly necessary only for clang, but not worth the extra detection infrastructure so we do it unconditionally for all compilers. For details, see https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=216770.

### CODE REVIEW

**Comment by mato** [comment]
@hannesm Could you give this a test on FreeBSD? It'll be quicker than me doing it.
@timbertson This fixes the C test case in #16 for me, can you confirm that it works for you?

**Comment by hannesm** [comment]
@mato thanks, this compiles fine with `FreeBSD clang version 5.0.0 (branches/release_50 310316) (based on LLVM 5.0.0svn)`, but fails to link a unikernel:
```
/home/hannes/.opam/ino64/lib/pkgconfig/../../lib/ocaml-freestanding/libnolibc.a(dtoa.o): In function `strtod':
dtoa.c:(.text+0x16c5): undefined reference to `__flt_rounds'
dtoa.c:(.text+0x28fa): undefined reference to `__flt_rounds'
```

**Comment by hannesm** [comment]
in FreeBSD, `__flt_rounds` is defined in `lib/libc/amd64/gen/flt_rounds.c` as:
```
/*
 * Written by J.T. Conklin, Apr 10, 1995
 * Public domain.
 */

#include <sys/cdefs.h>
__FBSDID("$FreeBSD$");

#include <float.h>

static const int map[] = {
        1,      /* round to nearest */
        3,      /* round to zero */
        2,      /* round to negative infinity */
        0       /* round to positive infinity */
};

int
__flt_rounds(void)
{
        int x;

        /* Assume that the x87 and the SSE unit agree on the rounding mode. */
        __asm("fnstcw %0" : "=m" (x));
        return (map[(x >> 10) & 0x03]);
}
```

**Comment by mato** [comment]
@hannesm I don't understand what code in `dtoa.c` is generating that call. AFAICT, it should only call `fegetround()` if `Honor_FLT_ROUNDS` is defined, which it's not.

**Comment by hannesm** [comment]
@mato solo5 copies `x86/float.h` which includes a `#define FLT_ROUNDS      __flt_rounds()`, and `FLT_ROUNDS` is used in `dtoa.c` (`#define Flt_Rounds FLT_ROUNDS`, where `Flt_rounds` is used in the code, and another `#define Rounding Flt_Rounds` where `Rounding` is used quite a lot in the code).

**Comment by mato** [comment]
@hannesm I've pushed a hacky fix for this in a6eb64a which reverts to the previously used value and does not depend on FLT_ROUNDS. Let me know if this fixes the linking on FreeBSD.

**Comment by hannesm** [comment]
@mato yes, this links now (tested with `tutorial/hello` from `mirage-skeleton`).  is there a test unikernel for `dtoa`?  I couldn't find any in `mirage-skeleton` - might be worth to add one!?

**Comment by mato** [comment]
@hannesm You can use @timbertson's code from https://github.com/mirage/ocaml-freestanding/issues/16#issue-223060795 to test, though that only tests `string_of_float`. I've not looked further to see what (if any) other code paths might use `strtod()` in the OCaml runtime. I've tried running that code against this version and it works as expected (no more `-NaN`).

Do you think this is OK to merge? It should make anything worse, fingers crossed, but then I'm not an expert on the floating point setup...

**Comment by hannesm** [comment]
@mato thanks again, the output looks good:
```
float=2.400000 -> string_of_float=2.4 -> parsed=2.400000
float=2.400000 -> printf-string  =2.400000 -> parsed=2.400000
float=1493895831.871153 -> string_of_float=1493895831.87 -> parsed=1493895831.870000
float=1493895831.871153 -> printf-string  =1493895831.871153 -> parsed=1493895831.871153
float=926038888360970.250000 -> string_of_float=9.26038888361e+14 -> parsed=926038888361000.000000
float=926038888360970.250000 -> printf-string  =926038888360970.250000 -> parsed=926038888360970.250000
float=926038888360970.250000 -> string_of_float=9.26038888361e+14 -> parsed=926038888361000.000000
float=926038888360970.250000 -> printf-string  =926038888360970.250000 -> parsed=926038888360970.250000
```

IMHO good to merge and it improves the current situation!

**Comment by mato** [comment]
I've also run Tim's test code and the output is fine, but will leave this a while to see if he can confirm that the original issue is fixed. If I don't get a response within a day or two then I'll merge it.

**Comment by timbertson** [comment]
Thanks @mato. I'm afraid I don't have time (or the right environment) to test this anytime soon, but it looks like it's working for you both, so I'd say go ahead 👍

**Comment by mato** [comment]
@timbertson Thanks for the feedback.

I've verified that GCC on Linux uses a fixed value of `1` for `FLT_ROUNDS` in `float.h`, have updated the last commit to reflect that comment and will merge shortly.
